### ISSUE TITLE
windows10 error：AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by yunfei2020** [kamilmahmood/fastzipfile#8]
`C:\Users\fz010>pip3 install fastzipfile
Collecting fastzipfile
  Using cached fastzipfile-2.2.tar.gz (4.1 kB)
Building wheels for collected packages: fastzipfile
  Building wheel for fastzipfile (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\program files\python\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\fz010\\AppData\\Local\\Temp\\pip-install-9p5psrf1\\fastzipfile_01a51666c3cd4ce1a93ebac8d8d5e9bf\\setup.py'"'"'; __file__='"'"'C:\\Users\\fz010\\AppData\\Local\\Temp\\pip-install-9p5psrf1\\fastzipfile_01a51666c3cd4ce1a93ebac8d8d5e9bf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\fz010\AppData\Local\Temp\pip-wheel-wajtft5t'
       cwd: C:\Users\fz010\AppData\Local\Temp\pip-install-9p5psrf1\fastzipfile_01a51666c3cd4ce1a93ebac8d8d5e9bf\
  Complete output (63 lines):
  d:\program files\python\python36\lib\site-packages\setuptools\dist.py:452: UserWarning: Normalizing 'v2.2' to '2.2'
    warnings.warn(tmpl.format(**locals()))
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  copying fastzipfile.py -> build\lib.win-amd64-3.6
  running build_ext
  building '_zipdecrypter' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\fz010\AppData\Local\Temp\pip-install-9p5psrf1\fastzipfile_01a51666c3cd4ce1a93ebac8d8d5e9bf\setup.py", line 41, in <module>
      zip_safe=False
    File "d:\program files\python\python36\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "d:\program files\python\python36\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "d:\program files\python\python36\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "d:\program files\python\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "d:\program files\python\python36\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "d:\program files\python\python36\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\program files\python\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "d:\program files\python\python36\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "d:\program files\python\python36\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\program files\python\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "d:\program files\python\python36\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "d:\program files\python\python36\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "d:\program files\python\python36\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "d:\program files\python\python36\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
      _build_ext.build_ext.build_extensions(self)
    File "d:\program files\python\python36\lib\distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "d:\program files\python\python36\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "d:\program files\python\python36\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
      _build_ext.build_extension(self, ext)
    File "d:\program files\python\python36\lib\distutils\command\build_ext.py", line 533, in build_extension
      depends=ext.depends)
    File "d:\program files\python\python36\lib\distutils\_msvccompiler.py", line 345, in compile
      self.initialize()
    File "d:\program files\python\python36\lib\distutils\_msvccompiler.py", line 238, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "d:\program files\python\python36\lib\site-packages\setuptools\msvc.py", line 312, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "d:\program files\python\python36\lib\site-packages\setuptools\msvc.py", line 264, in _msvc14_get_vc_env
      vcvarsall, vcruntime = _msvc14_find_vcvarsall(plat_spec)
    File "d:\program files\python\python36\lib\site-packages\setuptools\msvc.py", line 219, in _msvc14_find_vcvarsall
      _, best_dir = _msvc14_find_vc2017()
    File "d:\program files\python\python36\lib\site-packages\setuptools\msvc.py", line 197, in _msvc14_find_vc2017
      "-products", "*",
  AttributeError: 'str' object has no attribute 'decode'
  ----------------------------------------
  ERROR: Failed building wheel for fastzipfile
  Running setup.py clean for fastzipfile
Failed to build fastzipfile
Installing collected packages: fastzipfile
    Running setup.py install for fastzipfile ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\program files\python\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\fz010\\AppData\\Local\\Temp\\pip-install-9p5psrf1\\fastzipfile_01a51666c3cd4ce1a93ebac8d8d5e9bf\\setup.py'"'"'; __file__='"'"'C:\\Users\\fz010\\AppData\\Local\\Temp\\pip-install-9p5psrf1\\fastzipfile_01a51666c3cd4ce1a93ebac8d8d5e9bf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\fz010\AppData\Local\Temp\pip-record-71nceqo4\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\program files\python\python36\Include\fastzipfile'
         cwd: C:\Users\fz010\AppData\Local\Temp\pip-install-9p5psrf1\fastzipfile_01a51666c3cd4ce1a93ebac8d8d5e9bf\
    Complete output (65 lines):
    d:\program files\python\python36\lib\site-packages\setuptools\dist.py:452: UserWarning: Normalizing 'v2.2' to '2.2'
      warnings.warn(tmpl.format(**locals()))
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    copying fastzipfile.py -> build\lib.win-amd64-3.6
    running build_ext
    building '_zipdecrypter' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\fz010\AppData\Local\Temp\pip-install-9p5psrf1\fastzipfile_01a51666c3cd4ce1a93ebac8d8d5e9bf\setup.py", line 41, in <module>
        zip_safe=False
      File "d:\program files\python\python36\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "d:\program files\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\program files\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "d:\program files\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "d:\program files\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "d:\program files\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "d:\program files\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\program files\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "d:\program files\python\python36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "d:\program files\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\program files\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "d:\program files\python\python36\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "d:\program files\python\python36\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "d:\program files\python\python36\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "d:\program files\python\python36\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "d:\program files\python\python36\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "d:\program files\python\python36\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "d:\program files\python\python36\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "d:\program files\python\python36\lib\distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "d:\program files\python\python36\lib\distutils\_msvccompiler.py", line 345, in compile
        self.initialize()
      File "d:\program files\python\python36\lib\distutils\_msvccompiler.py", line 238, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "d:\program files\python\python36\lib\site-packages\setuptools\msvc.py", line 312, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "d:\program files\python\python36\lib\site-packages\setuptools\msvc.py", line 264, in _msvc14_get_vc_env
        vcvarsall, vcruntime = _msvc14_find_vcvarsall(plat_spec)
      File "d:\program files\python\python36\lib\site-packages\setuptools\msvc.py", line 219, in _msvc14_find_vcvarsall
        _, best_dir = _msvc14_find_vc2017()
      File "d:\program files\python\python36\lib\site-packages\setuptools\msvc.py", line 197, in _msvc14_find_vc2017
        "-products", "*",
    AttributeError: 'str' object has no attribute 'decode'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\program files\python\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\fz010\\AppData\\Local\\Temp\\pip-install-9p5psrf1\\fastzipfile_01a51666c3cd4ce1a93ebac8d8d5e9bf\\setup.py'"'"'; __file__='"'"'C:\\Users\\fz010\\AppData\\Local\\Temp\\pip-install-9p5psrf1\\fastzipfile_01a51666c3cd4ce1a93ebac8d8d5e9bf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\fz010\AppData\Local\Temp\pip-record-71nceqo4\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\program files\python\python36\Include\fastzipfile' Check the logs for full command output.
`

**Comment by kamilmahmood** [comment]
This library was not tested nor installed on windows before, but I have just installed it on Windows 10 with following environment and it worked fine

- python 3.8.0
- Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30136 for x86
- Visual C++ 2019 Redistributable Update
- Windows 10 SDK

Can you please share your environment for error reproducibility? 

You may also want to check this SO thread https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory

Thanks
